global:
  resolve_timeout: 30s

route:
  receiver: clearing-webhook
  group_by: [alertname]
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: clearing-webhook
    webhook_configs:
      - url: http://webhook:8081/alerts
        send_resolved: true
