version: '3.8'

services:
  sbt-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - sbt-cache:/root/.sbt
      - ivy-cache:/root/.ivy2
      - coursier-cache:/root/.cache/coursier

volumes:
  sbt-cache:
  ivy-cache:
  coursier-cache:
